## LetterTile is a piece of data that defines what a tile's attributes are.
class_name LetterTile
extends Resource

enum TileType {BASIC, STONED, LOCKED, BURNING, PLAGUED, CRUMBLING, JUNK, ETHEREAL, ORANGE}
enum TileLetter {A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z}
enum NotchTypes {EMPTY, REPEATING, ECHOING, VAPORIZING, WEIGHTED, INERT, GILDED, PHANTOM, FLAMING, REJUVENATING, REINFORCED, EAGER, PATIENT, QUICK, OVERLOADED, BALANCED, LOCAL, DISTANT, PRICKLY, POTENT, LEXICAL}

## The LetterTile's current TileType.
@export var type: TileType
## The LetterTile's original TileType.
@export var original_type: TileType
## The LetterTile's original TileLetter.
@export var true_letter: TileLetter
## The TileLetter that this LetterTile is played as.
@export var played_letter: TileLetter
## The TileLetter that this LetterTile appears to be.
@export var visual_letter: TileLetter
## The first additional letter that a Lexical Notch can add to this LetterTile.
@export var bonus_letter1 := ""
## The second additional letter that a Lexical Notch can add to this LetterTile.
@export var bonus_letter2 := ""
## The third additional letter that a Lexical Notch can add to this LetterTile.
@export var bonus_letter3 := ""
## The type of Notch in this LetterTile's first notch slot.
@export var notch1: NotchTypes
## The type of Notch in this LetterTile's second notch slot.
@export var notch2: NotchTypes
## The type of Notch in this LetterTile's third notch slot.
@export var notch3: NotchTypes
## The index of this LetterTile in the deck that contains it.
@export var tile_index: int					# Rename to deck_index?
## The index of this LetterTile in the player's racked tiles.
@export var grid_index: int
## The position target for this LetterTile's owner to move to.
@export var target: Vector2
## Boolean to determine whether or not this LetterTile is owned by the player.
@export var is_friendly := true

# Temporary and Ghost should be separate because temporary can be from Phantom or other sources,
# whereas Ghost is from Lexical

## Boolean to determine if a tile was generated by a Phantom Notch or any similar effect.
@export var is_temporary := 		false 			# Rename to is_token?
## Boolean to determine if a tile is one of the ghost tiles created by a Lexical Notch when added to a word.
@export var is_ghost := 			false			# Might be confusing with the attribute of GridTiles.
## Boolean to determine if a tile is inherently debuff immune. The Inert notch does not use this flag, as it absorbs debuffs.
@export var is_debuff_immune := 	false			# This is fine as-is. Good to have this as a flag.
## Not sure if this will say.
@export var is_inflicted := 		false			# 
## Boolean to determine if a tile should visibly appear to be Blank. This is used in Shops to add customized Tiles to the player's deck.
@export var is_blank := 			false			# For Shops.
## Boolean to determine if anything stops a tile from being playable.
@export var is_playable := 			true			# Does anything prevent this from being played?

### Flagging
# echoNUM determines if a tile has Echoed this draw. True means that it has not.
# Defaults to false due to Weighted tiles. Flag is set to true when drawn if the
# tile has the Echoing notch in the relevant slot.
## Boolean to determine if a tile has Echoed as a result of an Echoing notch being in Notch slot 1. Defaults to false.
var echo1 := false
## Boolean to determine if a tile has Echoed as a result of an Echoing notch being in Notch slot 2. Defaults to false.
var echo2 := false
## Boolean to determine if a tile has Echoed as a result of an Echoing notch being in Notch slot 3. Defaults to false.
var echo3 := false
## Boolean to determine if a tile has Echoed as a result of another effect, such as a relic. Defaults to false.
var special_echo := false
## Boolean to determine if any of the above flags have been activated in the process of playing this word. Defaults to false.
var echoed_this_word := false

# healNUM determines if a Rejuvenating tile has healed this combat.
# False means that it has not. Flag changes when activated.
## Boolean to determine if a Rejuvenating Notch in the first notch slot has activated this combat. Defaults to false.
var heal1 := false
## Boolean to determine if a Rejuvenating Notch in the second notch slot has activated this combat. Defaults to false.
var heal2 := false
## Boolean to determine if a Rejuvenating Notch in the third notch slot has activated this combat. Defaults to false.
var heal3 := false

# These flags determine combat states.
var no_buffer := false
var vaporized := false

## This determines how many turns this tile has been in your Rack for.
var current_age 	:= 0

### Other Data
## The number of times this Tile has been played.
var times_played 		:= 0
## The position of this Tile in the currently played word.
var word_index			:= 0
## The total length of the currently played word.
var word_length			:= 0

### Functions
## new_tile creates a tile based on the information given, for the purpose
## of creating the player's initial deck.
func new_tile	(_type, _letter, _notch1, _notch2, _notch3, _tile_index, _is_ghost: bool = false, \
				_is_debuff_immune: bool = false, _is_inflicted: bool = false, _is_blank: bool = false, \
				_is_playable: bool = true) -> LetterTile:
	type = _type
	original_type = _type
	true_letter = _letter
	played_letter = _letter
	visual_letter = _letter
	notch1 = _notch1
	notch2 = _notch2
	notch3 = _notch3
	tile_index = _tile_index
	is_ghost = _is_ghost
	is_debuff_immune = _is_debuff_immune
	is_blank = _is_blank
	is_playable = _is_playable
	return self

## generate_tile creates a tile to be added to the deck.
func generate_tile(_type, _letter, _notch1, _notch2, _notch3, _is_blank: bool = false) -> LetterTile:
	type = _type
	original_type = LetterTile.TileType.BASIC
	true_letter = _letter
	played_letter = _letter
	visual_letter = _letter
	notch1 = _notch1
	notch2 = _notch2
	notch3 = _notch3
	is_blank = _is_blank
	return self
